import = [
   #"~/.config/alacritty/catppuccin-frappe.toml"
  #"~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
[window]
opacity = 0.9
[font]
size = 13.0
normal = { family = "MesloLGS NF", style = "Regular" }
[selection]
save_to_clipboard = true
